---
openapi: 3.0.0
info:
  title: Proyecto Biometria
  description: API para el control de datos entre Arduino-Android-Web
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/Mari0x112/pbiometria/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /sesion:
    get:
      tags:
      - público
      summary: "Devuelve la sesión activa, si existe."
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/empty'
        "401":
          description: Error al encontrar la sesión.
        "5XX":
          description: Error del servidor.
    post:
      tags:
      - público
      summary: Crea una sesión para un usuario.
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/sesion_body'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/empty'
        "401":
          description: No autorizado
        "5XX":
          description: Error del servidor.
    delete:
      tags:
      - público
      summary: Elimina la sesión.
      responses:
        "200":
          description: OK
        "5XX":
          description: Error del servidor.
  /mediciones/{id_sensor}:
    get:
      tags:
      - cliente
      summary: "Devuelve las mediciones del sensor {id_sensor}"
      parameters:
      - name: id_sensor
        in: path
        description: ID numérico del sensor
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: OK
        "401":
          description: No autorizado.
        "404":
          description: No se encontró el sensor.
        "5XX":
          description: Error del servidor.
  /mediciones:
    get:
      tags:
      - cliente
      summary: Devuelve todas las mediciones almacenadas.
      responses:
        "200":
          description: OK
        "401":
          description: No autorizado.
        "404":
          description: No se encontró el sensor.
        "5XX":
          description: Error del servidor.
    post:
      tags:
      - cliente
      summary: Crea una instancia de una medición.
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/mediciones_body'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/empty'
        "401":
          description: No autorizado
        "5XX":
          description: Error del servidor.

components:
  schemas:
    empty:
      required:
    sesion_body:
      required:
      - email
      - password
      type: object
      properties:
        email:
          type: string
          example: example@mail.com
        password:
          type: string
          example: yourpassword
    mediciones_body:
      required:
      - ID_sensor
      - lat
      - lon
      - ppmO3
      - temp
      type: object
      properties:
        ID_sensor:
          type: integer
          example: 1
        ppmO3:
          type: integer
          example: 5
        temp:
          type: integer
          example: 26
        lat:
          type: number
        lon:
          type: number
